### PR TITLE
add nuxt.js to framework-guides

### PR DESCRIPTION
**Pull request by jakob30061**

### CODE REVIEW

**Comment by GriffinJohnston** [comment]
Thanks for the PR! I'll look over this once my brain is a little less fried (COVID).

**Comment by jakob30061** [comment]
No rush. Take your time and get well soon!

**Comment by jakob30061** [comment]
Hey, i hope you're feeling better after COVID. 
Did you have the time to look over this PR? If not, no worries.

**Comment by GriffinJohnston** [comment]
Hey @jakob30061 thanks for the reminder! I'm fully recovered, but still playing catch up with neglected work. Your PR looks good at first glance, but I need to test your instructions fully before merging, I'll try to do that this week sometime.

**Comment by GriffinJohnston** [comment]
Okay, finally got a second to try this out. LGTM!

**Pull request merged**
